---
title: "Climate Sewanee"
author: "Solomon Sakakeeny-Smith"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE)
#Load library
library(tidyverse)
#set working directory
setwd('/Users/solomonsakakeeny-smith/Desktop/solomon_datalab/Datalab_2024/climate_sewanee')
#making dataset
weather<-read_csv('sewanee_weather.csv')
```
# Introduction

### Average monthly precipitation from 2000-2024, grouped in 5 year periods
```{r}
#Make a Month and Year column
weather<-weather %>% 
  mutate(year=year(ymd(DATE)),
         month=month(ymd(DATE)),
         month_name=month.abb[month]) %>% 
  mutate(month_name=fct_reorder(month_name,month)) %>% 
  mutate(yrblock = case_when(
      year >= 2000 & year <= 2004  ~ "2000-2004",
      year >= 2005 & year <= 2009  ~ "2005-2009",
      year >= 2010 & year <= 2014  ~ "2010-2014",
      year >= 2015 & year <= 2019  ~ "2015-2019",
      year >= 2020 & year <= 2024  ~ "2020-2024",
      .default = "other"
    ))
# #Finding Monthly averages for year groups
# group1<-weather %>%
#   filter(yrblock=='2000-2004') %>%
#   group_by(month_name) %>%
#   summarise(average_monthy_rain_group1=mean(PRCP,na.rm = TRUE))
# group2<-weather %>%
#   filter(yrblock=='2005-2009') %>%
#   group_by(month_name) %>%
#   summarise(average_monthy_rain_group2=mean(PRCP,na.rm = TRUE))
# group3<-weather %>%
#   filter(yrblock=='2010-2014') %>%
#   group_by(month_name) %>%
#   summarise(average_monthy_rain_group3=mean(PRCP,na.rm = TRUE))
# group4<-weather %>%
#   filter(yrblock=='2015-2019') %>%
#   group_by(month_name) %>%
#   summarise(average_monthy_rain_group4=mean(PRCP,na.rm = TRUE))
# group5<-weather %>%
#   filter(yrblock=='2020-2024') %>%
#   group_by(month_name) %>%
#   summarise(average_monthy_rain_group5=mean(PRCP,na.rm = TRUE))
# #Make graph
# ggplot(data = group1,aes(x=month_name,y=average_monthy_rain_group1))+
#   geom_col(alpha=.5,fill='steelblue')+
#   labs(title = 'Average monthly precipitation from 2000-2004',x='Month',y='Average Precipitation (inches)')
# ggplot(data = group2,aes(x=month_name,y=average_monthy_rain_group2))+
#   geom_col(alpha=.5,fill='steelblue')+
#   labs(title = 'Average monthly precipitation from 2005-2009',x='Month',y='Average Precipitation (inches)')
# ggplot(data = group3,aes(x=month_name,y=average_monthy_rain_group3))+
#   geom_col(alpha=.5,fill='steelblue')+
#   labs(title = 'Average monthly precipitation from 2010-2014',x='Month',y='Average Precipitation (inches)')
# ggplot(data = group4,aes(x=month_name,y=average_monthy_rain_group4))+
#   geom_col(alpha=.5,fill='steelblue')+
#   labs(title = 'Average monthly precipitation from 2015-2019',x='Month',y='Average Precipitation (inches)')
# ggplot(data = group5,aes(x=month_name,y=average_monthy_rain_group5))+
#   geom_col(alpha=.5,fill='steelblue')+
#   labs(title = 'Average monthly precipitation from 2020-2024',x='Month',y='Average Precipitation (inches)')

weather_2.0<-weather %>% 
  group_by(yrblock,month_name) %>% 
  summarise(average_monthly_precipitation=mean(PRCP,na.rm=TRUE))
ggplot(data = weather_2.0,aes(x=month_name,y=average_monthly_precipitation))+
  geom_col(alpha=.5,fill='steelblue')+
  labs(title = 'Average monthly precipitation',x='Month',y='Average Precipitation (inches)')+
  facet_wrap(~yrblock,ncol=1)
  

```

